apply plugin: 'com.android.application'

android {
    namespace "com.omar.acer.musicalstructure" // Add this line
    compileSdkVersion 34
    defaultConfig {
        applicationId "com.omar.acer.musicalstructure"
        minSdkVersion 21
        targetSdkVersion 34
        versionCode 10
        versionName "1.5"
        resConfigs "en"
    }
    aaptOptions{
        cruncherEnabled = false
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), "proguard-rules.pro"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.media:media:1.6.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.documentfile:documentfile:1.0.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
